;
; pe21_ex1.asm
;
; Created: 9/28/2023 12:59:04 PM
; Author : tuan minh
;


; Replace with your application code
.ORG 0
.DEF TEMP = R17
.MACRO INITSTACK
		LDI R20, HIGH(RAMEND)
		OUT SPH, R20
		LDI R20, LOW(RAMEND)
		OUT SPL, R20
.ENDMACRO

		INITSTACK
		SBI DDRA, 0

MAIN:
		SBI PORTA, 0
		CALL DELAY_1ms
		CBI PORTA, 0
		CALL DELAY_1ms
		RJMP MAIN
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
DELAY_1ms:
		LDI TEMP, 131
		OUT TCNT0, TEMP ; INIT TCNT0 = 256 - 125 = 131
		LDI TEMP, 0x00 ; BYPASS T/C CONTROL REGISTER A
		OUT TCCR0A, TEMP
		LDI TEMP, 0x0B ; NORMAL MODE, CLK/64
		OUT TCCR0B, TEMP

LOOP:
		SBIS TIFR0, TOV0 ; SAMPLE T/C INTERRUPT FLAG REGISTER 
		RJMP LOOP
		LDI TEMP, 0
		OUT TCCR0B, TEMP
		SBI TIFR0, TOV0
		RET
